provisionerId: aws-provisioner-v1
workerType: github-worker
schedulerId: taskcluster-github
retries: 5
priority: highest
created: '2019-05-23T09:40:32.671Z'
deadline: '2019-05-24T09:40:32.671Z'
expires: '2019-06-20T09:40:32.671Z'
scopes: []
payload:
  image: grenade/opencloudconfig
  maxRunTime: 600
  command:
    - /bin/bash
    - '--login'
    - '-c'
    - >-
      pip install slugid taskcluster && python <(curl -s
      https://gist.githubusercontent.com/grenade/a2ff8966607583fbc1944fccc256a80c/raw/decision-task.py)
metadata:
  owner: grenade@mozilla.com
  source: 'https://gist.github.com/grenade/a2ff8966607583fbc1944fccc256a80c'
  name: decision-task
  description: a gist based task group
tags: {}
extra: {}