provisionerId: aws-provisioner-v1
workerType: github-worker
retries: 5
priority: highest
created: '2019-05-23T11:09:17.216Z'
deadline: '2019-05-24T11:09:17.216Z'
expires: '2019-06-20T11:09:17.216Z'
scopes:
  - 'queue:scheduler-id:taskcluster-github'
  - 'queue:create-task:medium:aws-provisioner-v1/gecko-t-win*'
  - 'queue:create-task:aws-provisioner-v1/gecko-t-win*'
  - 'queue:create-task:medium:aws-provisioner-v1/gecko-1-b-win*'
  - 'queue:create-task:aws-provisioner-v1/gecko-1-b-win*'
  - 'queue:task-group-id:taskcluster-github/*'
  - 'queue:schedule-task:taskcluster-github/*'
payload:
  image: python
  maxRunTime: 600
  features:
    taskclusterProxy: true
  artifacts:
    'public/results.json':
      path: results.json
      type: file
  command:
    - /bin/bash
    - '--login'
    - '-c'
    - >-
      pip install asyncio slugid taskcluster && python <(curl -s
      https://gist.githubusercontent.com/grenade/a2ff8966607583fbc1944fccc256a80c/raw/decision-task.py)
metadata:
  owner: grenade@mozilla.com
  source: 'https://gist.github.com/grenade/a2ff8966607583fbc1944fccc256a80c'
  name: decision-task
  description: a gist based task group
tags: {}
extra: {}