---
provisionerId: relops-3
workerType: decision
retries: 5
priority: highest
created: '2020-07-08T07:00:36.378Z'
deadline: '2020-07-08T10:00:36.378Z'
routes:
  - index.project.relops.worker-observation.decision
scopes:
  - 'queue:route:index.project.relops.worker-observation.*'
  - 'queue:scheduler-id:-'
  - 'queue:create-task:low:comm-t/t-win*'
  - 'queue:create-task:low:comm-1/b-win*'
  - 'queue:create-task:low:comm-3/b-win*'
  - 'queue:create-task:low:gecko-t/t-win*'
  - 'queue:create-task:low:gecko-1/b-win*'
  - 'queue:create-task:low:gecko-3/b-win*'
  - 'queue:create-task:low:mpd001-1/b-win*'
  - 'queue:create-task:low:mpd001-3/b-win*'
  - 'queue:create-task:low:nss-1/win*'
  - 'queue:create-task:low:nss-3/win*'
  - 'queue:create-task:low:relops-3/win*'
  - 'queue:task-group-id:taskcluster-github/*'
  - 'queue:schedule-task:taskcluster-github/*'
payload:
  image: python
  maxRunTime: 7200
  features:
    taskclusterProxy: true
  artifacts:
    public/results.json:
      path: results.json
      type: file
  command:
    - /bin/bash
    - '--login'
    - '-c'
    - >-
      python --version
      && pip install asyncio | grep -v "^[[:space:]]*$"
      && pip install pyyaml | grep -v "^[[:space:]]*$"
      && pip install slugid | grep -v "^[[:space:]]*$"
      && pip install taskcluster | grep -v "^[[:space:]]*$"
      && git clone --quiet https://gist.github.com/a2ff8966607583fbc1944fccc256a80c.git ./worker-observation
      && python ./worker-observation/decision-task.py
metadata:
  owner: grenade@mozilla.com
  source: 'https://gist.github.com/grenade/a2ff8966607583fbc1944fccc256a80c'
  name: '00 :: create-worker-tasks'
  description: create observation tasks on workers
tags: {}
extra: {}
