provisionerId: relops-3
workerType: decision
retries: 5
priority: highest
created: '2019-11-01T08:57:58.104Z'
deadline: '2019-11-02T08:57:58.104Z'
expires: '2019-11-29T08:57:58.104Z'
routes:
  - index.project.relops.worker-observation.decision
scopes:
  - 'queue:route:index.project.relops.worker-observation.*'
  - 'queue:scheduler-id:taskcluster-github'
  - 'queue:create-task:comm-t/t-win*'
  - 'queue:create-task:comm-1/b-win*'
  - 'queue:create-task:comm-3/b-win*'
  - 'queue:create-task:gecko-t/t-win*'
  - 'queue:create-task:gecko-1/b-win*'
  - 'queue:create-task:gecko-3/b-win*'
  - 'queue:create-task:mpd001-1/b-win*'
  - 'queue:create-task:mpd001-3/b-win*'
  - 'queue:create-task:nss-1/win*'
  - 'queue:create-task:nss-3/win*'
  - 'queue:create-task:relops-3/win*'
  - 'queue:task-group-id:taskcluster-github/*'
  - 'queue:schedule-task:taskcluster-github/*'
payload:
  image: python
  maxRunTime: 7200
  features:
    taskclusterProxy: true
  artifacts:
    public/results.json:
      path: results.json
      type: file
  command:
    - /bin/bash
    - '--login'
    - '-c'
    - >-
      python --version && pip install asyncio pyyaml slugid taskcluster && python <(curl -s
      https://gist.githubusercontent.com/grenade/a2ff8966607583fbc1944fccc256a80c/raw/decision-task.py)
metadata:
  owner: grenade@mozilla.com
  source: 'https://gist.github.com/grenade/a2ff8966607583fbc1944fccc256a80c'
  name: '00 :: create-worker-tasks'
  description: a gist based task group
tags: {}
extra: {}
