---
tasks:
- targets:
  - provisioner: comm-1
    workertype: b-win2012
    iterations: 2
  - provisioner: comm-3
    workertype: b-win2012
    iterations: 2
  - provisioner: comm-t
    workertype: t-win10-64
    iterations: 2
  - provisioner: comm-t
    workertype: t-win7-32
    iterations: 2
  - provisioner: gecko-1
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-3
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-gpu-s
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-source
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32-gpu
    iterations: 2
  - provisioner: mpd001-1
    workertype: b-win2012
    iterations: 2
  - provisioner: mpd001-3
    workertype: b-win2012
    iterations: 2
  - provisioner: nss-1
    workertype: win2012r2
    iterations: 2
  - provisioner: nss-3
    workertype: win2012r2
    iterations: 2
  - provisioner: relops-3
    workertype: win2019
    iterations: 2
  namespace: observe-software-versions
  name:
    prefix: '01 :: '
    suffix: " :: observe-software-versions"
  description:
    prefix: 'observe software versions on '
    suffix: ''
  owner: grenade@mozilla.com
  command:
  - mkdir .\public
  - chcp 65001 > nul && ver > .\public\windows-version.txt
  - chcp 65001 > nul && C:\mozilla-build\python\python.exe --version 2> .\public\python2-version.txt
  - chcp 65001 > nul && C:\mozilla-build\python3\python3.exe --version > .\public\python3-version.txt
  - >-
    chcp 65001 > nul && C:\mozilla-build\python\python.exe -c "exec(\"import
    platform;print platform.release()\")" >
    .\public\python2-platform-release.txt
  - >-
    chcp 65001 > nul && C:\mozilla-build\python3\python3.exe -c "exec(\"import
    platform;print(platform.release())\")" >
    .\public\python3-platform-release.txt
  - chcp 65001 > nul && wget.exe --version > .\public\wget-version.txt
  - chcp 65001 > nul && hg --version > .\public\hg-version.txt
  - chcp 65001 > nul && C:\generic-worker\generic-worker.exe --version > .\public\generic-worker-version.txt
  - chcp 65001 > nul && wmic os get servicepackmajorversion > .\public\servicepack-major-version.txt
  artifacts:
  - type: file
    name: public/windows-version.txt
    path: public/windows-version.txt
    regex:
      match: '\d+\.\d+\.\d+'
      group: 0
  - type: file
    name: public/python2-version.txt
    path: public/python2-version.txt
    regex:
      match: '\d+\.\d+\.\d+'
      group: 0
  - type: file
    name: public/python3-version.txt
    path: public/python3-version.txt
    regex:
      match: '\d+\.\d+\.\d+'
      group: 0
  - type: file
    name: public/python2-platform-release.txt
    path: public/python2-platform-release.txt
  - type: file
    name: public/python3-platform-release.txt
    path: public/python3-platform-release.txt
  - type: file
    name: public/wget-version.txt
    path: public/wget-version.txt
    regex:
      match: '\d+\.\d+\.\d+'
      group: 0
  - type: file
    name: public/hg-version.txt
    path: public/hg-version.txt
    regex:
      match: '\d+\.\d+\.\d+'
      group: 0
  - type: file
    name: public/generic-worker-version.txt
    path: public/generic-worker-version.txt
    regex:
      match: '\d+\.\d+\.\d+'
      group: 0
  - type: file
    name: public/servicepack-major-version.txt
    path: public/servicepack-major-version.txt
    encoding: utf-16
    line: 1
  features:
    taskclusterProxy: true
  maxruntime: 600
- targets:
  - provisioner: gecko-1
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-3
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-gpu-s
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-source
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32-gpu
    iterations: 2
  - provisioner: mpd001-1
    workertype: b-win2012
    iterations: 2
  - provisioner: mpd001-3
    workertype: b-win2012
    iterations: 2
  - provisioner: relops-3
    workertype: win2019
    iterations: 2
  namespace: observe-occ-config
  name:
    prefix: '02 :: '
    suffix: " :: observe-occ-config"
  description:
    prefix: 'observe occ configuration on '
    suffix: ''
  owner: grenade@mozilla.com
  command:
  - mkdir .\public
  - chcp 65001 > nul && reg query HKLM\SOFTWARE\Mozilla\OpenCloudConfig\Source /v Organisation > .\public\occ-source-organisation.txt
  - chcp 65001 > nul && reg query HKLM\SOFTWARE\Mozilla\OpenCloudConfig\Source /v Repository > .\public\occ-source-repository.txt
  - chcp 65001 > nul && reg query HKLM\SOFTWARE\Mozilla\OpenCloudConfig\Source /v Revision > .\public\occ-source-revision.txt
  artifacts:
  - type: file
    name: public/occ-source-organisation.txt
    path: public/occ-source-organisation.txt
    line: 2
    split:
      separator: "    "
      index: 2
  - type: file
    name: public/occ-source-repository.txt
    path: public/occ-source-repository.txt
    line: 2
    split:
      separator: "    "
      index: 2
  - type: file
    name: public/occ-source-revision.txt
    path: public/occ-source-revision.txt
    line: 2
    split:
      separator: "    "
      index: 2
  features:
    taskclusterProxy: true
  maxruntime: 600
- targets:
  - provisioner: gecko-t
    workertype: t-win10-64-gpu-s
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32-gpu
    iterations: 2
  namespace: observe-nvidia-driver-version
  name:
    prefix: '03 :: '
    suffix: " :: observe-nvidia-driver-version"
  description:
    prefix: 'observe nvidia driver version on '
    suffix: ''
  owner: grenade@mozilla.com
  command:
  - mkdir .\public
  - chcp 65001 > nul && "C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi" --query-gpu=driver_version --format=csv > .\public\nvidia-driver-version.csv
  - chcp 65001 > nul && "C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi" > .\public\nvidia-driver-version.txt
  artifacts:
  - type: file
    name: public/nvidia-driver-version.csv
    path: public/nvidia-driver-version.csv
  - type: file
    name: public/nvidia-driver-version.txt
    path: public/nvidia-driver-version.txt
  features:
    taskclusterProxy: true
  maxruntime: 600
- targets:
  - provisioner: gecko-1
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-3
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-gpu-s
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-source
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32-gpu
    iterations: 2
  namespace: observe-chrome-version
  name:
    prefix: '04 :: '
    suffix: " :: observe-chrome-version"
  description:
    prefix: 'observe chrome version on '
    suffix: ''
  owner: grenade@mozilla.com
  command:
  - mkdir .\public
  - chcp 65001 > nul && wget -O .\get-chrome-version.cmd https://gist.githubusercontent.com/grenade/a2ff8966607583fbc1944fccc256a80c/raw/get-chrome-version.cmd
  - >-
    chcp 65001 > nul && .\get-chrome-version.cmd > .\public\chrome-version.txt
  artifacts:
  - type: file
    name: public/chrome-version.txt
    path: public/chrome-version.txt
  features:
    taskclusterProxy: true
  maxruntime: 600
- targets:
  - provisioner: comm-1
    workertype: b-win2012
    iterations: 2
  - provisioner: comm-3
    workertype: b-win2012
    iterations: 2
  - provisioner: comm-t
    workertype: t-win10-64
    iterations: 2
  - provisioner: comm-t
    workertype: t-win7-32
    iterations: 2
  - provisioner: gecko-1
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-3
    workertype: b-win2012
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-gpu-s
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win10-64-source
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32
    iterations: 2
  - provisioner: gecko-t
    workertype: t-win7-32-gpu
    iterations: 2
  - provisioner: mpd001-1
    workertype: b-win2012
    iterations: 2
  - provisioner: mpd001-3
    workertype: b-win2012
    iterations: 2
  - provisioner: relops-3
    workertype: win2019
    iterations: 2
  namespace: observe-filesystem
  name:
    prefix: '05 :: '
    suffix: " :: observe-filesystem"
  description:
    prefix: 'observe filesystem on '
    suffix: ''
  owner: grenade@mozilla.com
  command:
  - mkdir .\public
  - 'chcp 65001 > nul && tree c: /f /a > .\public\filesystem-drive-c.txt'
  - 'chcp 65001 > nul && tree y: /f /a > .\public\filesystem-drive-y.txt'
  - 'chcp 65001 > nul && tree z: /f /a > .\public\filesystem-drive-z.txt'
  artifacts:
  - type: file
    name: public/filesystem-drive-c.txt
    path: public/filesystem-drive-c.txt
  - type: file
    name: public/filesystem-drive-y.txt
    path: public/filesystem-drive-y.txt
  - type: file
    name: public/filesystem-drive-z.txt
    path: public/filesystem-drive-z.txt
  features:
    taskclusterProxy: true
  maxruntime: 600